# Generated by Django 5.1 on 2025-10-25 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkBox3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی های محصول',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='FooterLinkBox3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.footerlinkbox3', verbose_name='دسته بندی'),
        ),
    ]
