# Generated by Django 5.1 on 2025-10-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_footerlinkbox3_product_footerlinkbox3'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlinkbox3',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
    ]
