# Generated by Django 5.1 on 2025-10-30 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_footerlinkbox3_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlinkbox3',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.footerlinkbox3', verbose_name='دسته والد'),
        ),
        migrations.AlterField(
            model_name='footerlinkbox3',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='URL'),
        ),
    ]
