# Generated by Django 5.1 on 2025-02-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('price2', models.IntegerField(blank=True, null=True, verbose_name='قیمت بدون تخفیف')),
                ('is_available', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product')),
                ('short_description', models.CharField(db_index=True, max_length=360, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(db_index=True, verbose_name='توضیحات اصلی')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=True, verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'محصول home',
                'verbose_name_plural': 'محصولات home',
            },
        ),
    ]
