# Generated by Django 5.1 on 2025-12-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAboutCaffe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='تیتر مطلب')),
                ('publish_data', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product')),
            ],
            options={
                'verbose_name': 'مطالب خواندنی',
                'verbose_name_plural': 'مطالب های خواندنی',
            },
        ),
        migrations.AlterField(
            model_name='footerlinkbox2',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.footerlinkbox2', verbose_name='والد محصول'),
        ),
    ]
