# Generated by Django 5.1 on 2025-02-11 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkBox2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی محصولات',
                'verbose_name_plural': 'دسته بندی های محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Footer_link_box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.footerlinkbox2', verbose_name='دسته بندی'),
        ),
    ]
