# Generated by Django 5.1 on 2025-11-18 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'وزن محصول',
                'verbose_name_plural': 'وزن محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantgr', to='product.productgr')),
            ],
            options={
                'verbose_name': 'جزئیات محصول',
                'verbose_name_plural': 'جزئیات محصولات',
            },
        ),
    ]
