# Generated by Django 5.1 on 2025-11-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productgr_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantgr', to='product.productgr'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product'),
        ),
    ]
