# Generated by Django 5.1 on 2025-11-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productvariant_product2_alter_productvariant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgr',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
