# Generated by Django 5.1 on 2025-02-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_setting',
            name='site_logo_fool',
            field=models.ImageField(default='your_default_logo_url', max_length=255, upload_to='images/site_setting/', verbose_name='لوگو اسم سایت'),
        ),
    ]
