# Generated by Django 5.1 on 2025-02-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_site_setting_site_logo_fool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_setting',
            name='site_logo_fool',
            field=models.FileField(default='your_default_logo_url', max_length=255, upload_to='images/site_setting/', verbose_name='لوگو اسم سایت'),
        ),
    ]
