# Generated by Django 5.1 on 2025-02-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_alter_site_setting_site_logo_fool'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_setting',
            name='instagram',
            field=models.URLField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='site_setting',
            name='telegram',
            field=models.URLField(blank=True, max_length=20, null=True),
        ),
    ]
