# Generated by Django 5.1 on 2025-02-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_site_setting_instagram_site_setting_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_setting',
            name='telephone',
            field=models.CharField(max_length=100, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='مبایل'),
        ),
    ]
