# Generated by Django 5.1 on 2025-02-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_site_setting_telephone_alter_site_setting_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_setting',
            name='instagram_URL',
            field=models.URLField(blank=True, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='site_setting',
            name='telegram_URL',
            field=models.URLField(blank=True, null=True, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='URL اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='URL تلگرام'),
        ),
    ]
