# Generated by Django 5.1 on 2025-02-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_site_setting_instagram_url_site_setting_telegram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_setting',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='instagram_URL',
            field=models.URLField(blank=True, null=True, verbose_name='اینستاگرام URL'),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='site_setting',
            name='telegram_URL',
            field=models.URLField(blank=True, null=True, verbose_name='تلگرام URL'),
        ),
    ]
