# Generated by Django 5.1 on 2025-10-30 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی بلاگ',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای بلاگ',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مطلب')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('short_description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('content', models.TextField(verbose_name='محتوای مطلب')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='تصویر مطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='about_caffee.blogcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مطلب بلاگ',
                'verbose_name_plural': 'مطالب بلاگ',
                'ordering': ['-created_at'],
            },
        ),
    ]
