# Generated by Django 5.1 on 2025-11-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_caffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='تصویر دسته بندی'),
        ),
    ]
