# Generated by Django 5.1 on 2025-11-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_paide',
            new_name='is_paid',
        ),
    ]
