# Generated by Django 5.1 on 2025-12-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0002_rename_is_paide_order_is_paid'),
        ('product', '0011_product_price2_currency_product_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productvariant'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
